language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - ~/.selenium-assistant

before_install:
  - nvm install node

install:
  - npm install web-push-testing-service@0.3.2 -g

before_script:
  - web-push-testing-service start wpts

script:
  - ./gradlew check

after_script:
  - web-push-testing-service stop wpts

